FROM python:3.10.2-slim-bullseye
RUN apt-get update -y && apt-get upgrade -y && apt-get install gcc -y
RUN pip install --upgrade pip

COPY requirements.txt /srv/
RUN pip install -r /srv/requirements.txt
COPY docker/entrypoint.sh /srv/
COPY web/*.py /srv/web/
COPY core/*.py /srv/core/
COPY core/linguistic-data/* /srv/core/linguistic-data/

ENTRYPOINT srv/entrypoint.sh


