FROM python:3.9.1-slim-buster
RUN apt-get update -y && apt-get upgrade -y
RUN pip install --upgrade pip

COPY requirements.txt /srv/
RUN pip install -r /srv/requirements.txt
COPY docker/entrypoint.sh /srv/
COPY web/*.py /srv/web/
COPY web/diccionari.txt /srv/web/
COPY web/segment.srx /srv/web/

ENTRYPOINT srv/entrypoint.sh


